from openai import OpenAI
client = OpenAI(api_key='')

voices = ['alloy', 'echo', 'fable', 'onyx', 'nova', 'shimmer']
sentences = [
    "Magnificent vistas unfold across the valley, revealing nature's unspoiled beauty and tranquility.",
    "Several birds perched on the ancient oak, singing melodiously at dawn's first light.",
    "Beneath starlit skies, the campfire crackles, casting shadows on our cheerful faces.",
    "Navigating through the bustling market, vibrant colors and rich aromas fill the air.",
    "Wispy clouds drift lazily over the serene lake, reflecting the vibrant sunset.",
    "Every evening, grandma shares fascinating stories from her youth, filled with wisdom.",
    "Contemporary artists often seek inspiration from urban landscapes and their dynamic energies.",
    "Powerful waves crash against the rocky shore, spraying mist into the brisk wind.",
    "During the festival, locals performed traditional dances, wearing colorful, intricate costumes.",
    "Inventive chefs create unique dishes by blending exotic spices with fresh ingredients.",
    "Children's laughter echoes in the park as they chase after fluttering butterflies.",
    "Frost glistens on the windowpane, painting a delicate tapestry of icy filigree.",
    "Musicians from around the globe gathered to celebrate diverse cultures through song.",
    "Historic landmarks tell the tales of a city shaped by time and events.",
    "Deep in the forest, the hidden waterfall remains an untouched slice of paradise.",
    "Quantum physics explores the complexities of particles smaller than atoms in nature.",
    "Crisp autumn leaves rustle underfoot, creating a symphony of sounds with each step.",
    "Eager students discuss philosophical theories, striving to unlock the mysteries of existence.",
    "Jazz bands fill the night air with smooth melodies under the city lights.",
    "In remote villages, local artisans craft goods with techniques passed down generations.",
    "During spring, cherry blossoms frame the bustling streets with their delicate pink hues.",
    "Endangered species require protection to ensure their survival for future generations to admire.",
    "Adventurers trek across rugged terrain, seeking thrills in nature’s challenging embrace.",
    "Experts debate the implications of artificial intelligence on future job markets globally.",
    "Sudden rain showers bring relief to the parched land, invigorating the surrounding greenery.",
    "Culinary experts often experiment with molecular gastronomy to dazzle the palate and senses.",
    "Every leap year brings about unique traditions and superstitions in various cultures.",
    "Volcanic eruptions demonstrate Earth’s raw power and the creation of new landforms.",
    "Ancient manuscripts reveal insights about civilizations long vanished from the world stage.",
    "Marine biologists study the diverse ecosystems within the ocean's mysterious depths.",
    "Athletes from different nations compete with spirit and determination in the Olympic Games.",
    "Photographers capture fleeting moments, turning them into memories that can last forever.",
    "Librarians dedicate their lives to preserving knowledge and fostering a love of reading.",
    "Bright comets occasionally grace our night sky, inspiring awe and wonder worldwide.",
    "Artisans use recycled materials to create functional art, promoting sustainability and creativity.",
    "During winter, cozy firesides become the preferred gathering spots for family and friends.",
    "Complex algorithms determine what appears in social media feeds, influencing public opinion.",
    "Wildflowers bloom profusely along the highway, creating a vivid display of nature’s resilience.",
    "Migratory birds navigate thousands of miles using the Earth's magnetic field as a guide.",
    "Urban planners design cities to be more walkable, enhancing residents' quality of life.",
    "Cybersecurity experts constantly update defenses to protect against evolving online threats.",
    "Deserts, while harsh environments, host a surprising array of adapted plant and animal life.",
    "Sculptors shape raw materials into stunning works that express human emotion and creativity.",
    "Financial analysts scrutinize market trends to advise clients on investment strategies effectively.",
    "Distant galaxies intrigue astronomers with their mysteries and the potential for unknown life forms.",
    "Rainforests are critical to the planet’s health, producing oxygen and housing diverse species.",
    "Philanthropists contribute to society by supporting initiatives that address pressing global issues.",
    "Professional gamers compete in esports tournaments, drawing huge crowds and online viewerships.",
    "Sustainable farming practices help maintain soil health and produce crops more efficiently.",
    "Underwater caves offer a portal to an otherworldly realm of beauty and silence.",
    "Biologists release endangered turtles back to the ocean, giving them a chance at survival.",
    "Innovative startups disrupt traditional industries by introducing groundbreaking technologies and solutions.",
    "Classical orchestras resonate through concert halls, bringing timeless compositions to life.",
    "Meteorologists predict weather patterns, providing crucial information for agriculture and safety.",
    "Ancient philosophers pondered questions about existence, knowledge, and ethics that still resonate today.",
    "Local markets sell handmade goods that embody the cultural heritage of their communities.",
    "Researchers delve into the human genome, seeking clues to cure genetic diseases.",
    "Psychologists study human behavior, aiming to understand what motivates and influences our actions.",
    "Rare astronomical events, like solar eclipses, draw crowds of enthusiasts and scientists alike.",
    "Innovative architecture integrates sustainable elements to minimize environmental impact and maximize efficiency.",
    "Museums curate exhibits that challenge visitors' perspectives and inspire curiosity about the world.",
    "Activists advocate for social justice, striving to make the world a more equitable place.",
    "Documentaries expose hidden truths, sparking discussions and possibly prompting societal change.",
    "Nutritionists recommend diverse diets to ensure all essential nutrients are consumed for health.",
    "Potters shape clay into beautiful pottery, each piece unique and filled with character.",
    "Festivals celebrate the arts, showcasing local and international talent in a vibrant atmosphere.",
    "Veterinarians care deeply for animals, often going beyond to ensure their health and well-being.",
    "Innovative lighting designs enhance urban nightscapes, creating safe and inviting environments.",
    "Geologists study rock formations to understand Earth's history and predict future changes.",
    "Poets capture the essence of emotions and experiences with their concise and powerful words.",
    "Entrepreneurs face challenges head-on, turning ideas into successful businesses with perseverance.",
    "Teachers inspire students, igniting curiosity and fostering a lifelong love of learning.",
    "Chefs master culinary techniques to transform simple ingredients into exquisite dishes.",
    "Biotech firms develop drugs to treat rare diseases, often using cutting-edge technology.",
    "Fashion designers blend art and functionality, setting trends that captivate people globally.",
    "Dancers express stories through movement, communicating emotions that transcend language barriers.",
    "Ethical hackers identify vulnerabilities in systems, helping to improve cybersecurity measures.",
    "Astronauts undergo rigorous training to prepare for the challenges of space exploration.",
    "Volunteers make significant impacts, dedicating their time to helping those in need.",
    "Historians uncover lost narratives, piecing together events that shaped our current world.",
    "Engineers solve complex problems, from building bridges to developing renewable energy solutions.",
    "Magicians captivate audiences with illusions, creating moments of wonder and disbelief.",
    "Urban gardens transform rooftops into green oases, offering respite in concrete jungles.",
    "Veteran journalists pursue truth, often in the face of considerable risks and challenges.",
    "Public speakers captivate audiences, conveying messages that inspire and motivate change.",
    "Non-profit organizations work tirelessly to alleviate poverty and improve living conditions worldwide.",
    "Virtual reality experiences immerse users in digital worlds, revolutionizing entertainment and education.",
    "Wildlife photographers capture stunning images of animals in their natural habitats, raising awareness.",
    "Filmmakers craft stories that resonate with audiences, leaving lasting impressions through visuals and sound.",
    "Surgeons perform life-saving operations with precision and care, often under intense pressure.",
    "Composers create symphonies that evoke deep emotional responses from listeners across the globe.",
    "Revitalizing community centers foster strong bonds among residents, enhancing local collaboration and support.",
    "Glaciers slowly carve through ancient landscapes, shaping valleys and fjords over millennia.",
    "Economists analyze fiscal policies to predict their impacts on national and global economies.",
    "Professional critics review films, books, and art, influencing public opinion and cultural trends.",
    "Skilled artisans craft custom furniture from reclaimed wood, emphasizing beauty and sustainability.",
    "Neuroscientists explore the complexities of the brain, seeking insights into cognitive functions.",
    "Restaurateurs design welcoming spaces where people enjoy global cuisines in a local setting.",
    "Quantum computing promises to revolutionize industries by solving complex problems more efficiently.",
    "Traditional puppeteers keep ancient arts alive, captivating audiences with stories and skilled manipulations.",
    "Botanists travel to remote rainforests to catalog new plant species previously unknown to science.",
    "Strategic thinkers develop game-changing plans that navigate companies through competitive and challenging landscapes.",
    "Digital artists utilize advanced software to create stunning visual effects for blockbuster movies.",
    "Rural health clinics improve access to medical services for underserved populations in remote areas.",
    "Organic coffee farms promote sustainable agriculture by avoiding pesticides and supporting fair trade practices.",
    "Ethical debates arise over the use of drones in surveillance, weighing privacy against security.",
    "Fitness coaches encourage holistic approaches to health, integrating physical and mental wellness routines.",
    "Language experts teach indigenous languages, preserving cultural heritage for future generations to appreciate.",
    "Archaeologists unearth artifacts that shed light on the daily lives of ancient civilizations.",
    "Fashion icons set trends at prestigious global events, influencing what we wear each season.",
    "Diplomats negotiate international treaties, striving to maintain peace and cooperation among nations.",
    "Coding bootcamps equip students with the skills necessary for careers in technology sectors.",
    "Graphic novels combine art and narrative, offering a unique medium for storytelling.",
    "Marathon runners train rigorously, pushing their endurance to the limits in races worldwide.",
    "Bird watchers gather at sanctuaries to observe rare species during migratory seasons.",
    "Independent filmmakers craft compelling narratives on limited budgets, often earning critical acclaim.",
    "Deep-sea explorers map the ocean floor, discovering mysterious landscapes and new marine life.",
    "Herbalists use ancient knowledge to prepare natural remedies from plants and herbs.",
    "Urban renewal projects transform decaying areas into vibrant hubs of activity and culture.",
    "Symphony conductors lead orchestras through intricate performances, blending instruments into harmonious sounds."
]

j = len(voices)
for voice in voices:
    for i in range(20):
        speech_file_path = f"./data/OpenAI/{voice+'_'+str(i)}.wav"
        response = client.audio.speech.create(
          model="tts-1-hd",
          voice=voice,
          input=sentences[j*10+i]
        )
    
        response.stream_to_file(speech_file_path)
    j += 1